// src/lib/components/main-nav.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { cn } from "$lib/utils";
  import * as siteConfig from "$lib/config/site";
  import { Icons } from "./icons";
</script>

<div class="mr-4 hidden md:flex">
  <a href="/" class="mr-6 flex items-center space-x-2">
    <Icons.logo class="h-6 w-6" />
    <span class="hidden font-bold sm:inline-block">
      {siteConfig.name}
    </span>
  </a>
  <nav class="flex items-center space-x-6 text-sm font-medium">
    {#each siteConfig.mainNav as navItem}
      <a
        href={navItem.href}
        class={cn(
          "transition-colors hover:text-foreground/80",
          $page.url.pathname === navItem.href ? "text-foreground" : "text-foreground/60",
        )}
      >
        {navItem.title}
      </a>
    {/each}
  </nav>
</div>

// src/components/main-nav.tsx
"use client";

import * as React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";

import { cn } from "@/lib/utils";
import * as Icons from "./icons";

export function MainNav({
  routeLinks,
}: { routeLinks: { title: string; href: string }[] }) {
  const pathname = usePathname();

  return (
    <div className="mr-4 hidden md:flex">
      <Link href="/" className="mr-6 flex items-center space-x-2">
        <Icons.Logo className="h-6 w-6" />
        <span className="hidden font-bold sm:inline-block">Salen</span>
      </Link>
      <nav className="flex items-center gap-4 text-sm lg:gap-6">
        {routeLinks.map(({ href, title }) => (
          <Link
            key={href}
            href={href}
            className={cn(
              "transition-colors hover:text-foreground/80",
              pathname.startsWith(href)
                ? "text-foreground"
                : "text-foreground/60",
            )}
          >
            {title}
          </Link>
        ))}
      </nav>
    </div>
  );
}
