// src/lib/components/site-footer.svelte
<script>
  import * as siteConfig from "$lib/config/site";
  import { Icons } from "./icons";
  import { LightSwitch } from "./light-switch";
</script>

<footer>
  <div class="mx-auto max-w-7xl p-4 md:flex md:items-center md:justify-between md:p-8">
    <div class="flex items-center justify-center space-x-6 md:order-2">
      <a href={siteConfig.links.allaBolag} class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Allabolag</span>
        <Icons.circleDollarSign class="h6 w-6" />
      </a>
      <a href={siteConfig.links.facebook} class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Facebook</span>
        <Icons.facebook class="h6 w-6" />
      </a>
      <a href={siteConfig.links.github} class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">GitHub</span>
        <Icons.github class="h6 w-6" />
      </a>
      <div class="ml-8">
        <LightSwitch />
      </div>
    </div>
    <div class="my-8 md:order-1 md:my-0">
      <p class="text-center text-xs leading-5 text-gray-500">
        &copy; {new Date().getFullYear()} Salens Samfällighetsförening
      </p>
    </div>
  </div>
</footer>

// src/components/site-footer.tsx
import Link from "next/link";
import { Icons } from "./icons";

export function SiteFooter() {
  const links = {
    allaBolag:
      "https://www.allabolag.se/7179068213/salens-samfallighetsforening",
    umeaEnergiDriftInfo: "https://driftinfo.umeaenergi.se/help",
  };

  return (
    <footer id="footer">
      <hr className="w-11/12 mx-auto" />

      <section className="container py-20 grid grid-cols-2 md:grid-cols-4 xl:grid-cols-6 gap-x-12 gap-y-8">
        <div className="col-span-full xl:col-span-2">
          <Link
            href="/"
            className="mr-6 flex items-center space-x-2"
            rel="noopener noreferrer"
          >
            <Icons.logo className="h-6 w-6" />
            <span className="font-bold text-xl inline-block">Salen</span>
          </Link>
        </div>

        <div className="flex flex-col gap-2">
          <h3 className="font-bold text-lg">Links</h3>
          <div>
            <a
              rel="noreferrer noopener"
              href={links.allaBolag}
              className="opacity-60 hover:opacity-100"
            >
              Alla bolag
            </a>
          </div>

          <div>
            <a
              rel="noreferrer noopener"
              href={links.umeaEnergiDriftInfo}
              className="opacity-60 hover:opacity-100"
            >
              Umeå Energi driftinfo
            </a>
          </div>
        </div>
      </section>

      <section className="container pb-14 text-center">
        <h3>&copy; {new Date().getFullYear()} Salens Samfällighetsförening</h3>
      </section>
    </footer>
  );
}
