// src/app/(main)/(auth)/login/page.tsx
import React, { Suspense } from "react";
import type { Metadata } from "next";
import Link from "next/link";

import { getMeUser } from "@/lib/utilities/getMeUser";
import { LoginForm } from "./login-form";

import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";
import * as Icons from "@/components/icons";

export const metadata: Metadata = {
	title: "Login",
	description: "Login to your account",
};

export default async function LoginPage() {
	await getMeUser({
		validUserRedirect: `/posts?message=${encodeURIComponent(
			"You are already logged in.",
		)}`,
	});

	return (
		<div className="container flex h-screen w-screen flex-col items-center justify-center">
			<Link
				href="/"
				className={cn(
					buttonVariants({ variant: "ghost" }),
					"absolute left-4 top-4 md:left-8 md:top-8",
				)}
			>
				<>
					<Icons.ArrowLeft className="mr-2 h-4 w-4" />
					Back
				</>
			</Link>
			<div className="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
				<div className="flex flex-col space-y-2 text-center">
					<Icons.Logo className="mx-auto h-6 w-6" />
					<h1 className="text-2xl font-semibold tracking-tight">
						Welcome back
					</h1>
					<p className="text-sm text-muted-foreground">
						Enter your email to sign in to your account
					</p>
				</div>
				<Suspense>
					<LoginForm />
				</Suspense>
				<p className="px-8 text-center text-sm text-muted-foreground">
					<Link
						href="/forgot-password"
						className="hover:text-brand underline underline-offset-4"
					>
						Forgot password?
					</Link>
				</p>
			</div>
		</div>
	);
}

// src/routes/auth/login/+page.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import { buttonVariants } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";
  import { Icons } from "$lib/components/icons";
</script>

<svelte:head>
  <title>Logga in</title>
</svelte:head>

<div class="container flex h-screen w-screen flex-col items-center justify-center">
  <a
    href="/"
    class={cn(buttonVariants({ variant: "ghost" }), "absolute left-4 top-4 md:left-8 md:top-8")}
  >
    <Icons.arrowLeft class="mr-2 h-4 w-4" />
    Tillbaka
  </a>
  <div class="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
    <div class="flex flex-col space-y-2 text-center">
      <Icons.logo class="mx-auto h-6 w-6" />
      <h1 class="text-2xl font-semibold tracking-tight">Välkommen tillbaka!</h1>
      <p class="text-sm text-muted-foreground">
        Fyll i dina uppgifter för att logga in på ditt konto
      </p>
    </div>

    <div class="grid gap-6">
      <form method="post" action="/auth/login">
        <div class="grid gap-2">
          <div class="grid gap-1">
            <Label for="email">Epost</Label>
            <Input
              id="email"
              name="email"
              placeholder="name@example.com"
              type="email"
              autocapitalize="none"
              autocomplete="email"
              autocorrect="off"
            />
          </div>

          <div class="grid gap-1">
            <Label for="password">Lösenord</Label>
            <Input id="password" name="password" type="password" />
            <button class={cn(buttonVariants())}>Logga in</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
