// src/components/mobile-nav.tsx
"use client";

import * as React from "react";
import Link from "next/link";
import type { LinkProps } from "next/link";
import { useRouter } from "next/navigation";

import { cn } from "@/lib/utils";
import * as Icons from "@/components/icons";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

export function MobileNav() {
	const [open, setOpen] = React.useState(false);

	return (
		<Sheet open={open} onOpenChange={setOpen}>
			<SheetTrigger asChild>
				<Button
					variant="ghost"
					className="mr-2 px-0 text-base hover:bg-transparent focus-visible:bg-transparent focus-visible:ring-0 focus-visible:ring-offset-0 md:hidden"
				>
					<Icons.Menu />
					<span className="sr-only">Toggle Menu</span>
				</Button>
			</SheetTrigger>
			<SheetContent side="left" className="pr-0">
				<MobileLink
					href="/"
					className="flex items-center"
					onOpenChange={setOpen}
				>
					<Icons.Logo className="mr-2 h-4 w-4" />
					<span className="font-bold">Salen</span>
				</MobileLink>
				<ScrollArea className="my-4 h-[calc(100vh-8rem)] pb-10 pl-6">
					<div className="flex flex-col space-y-3">
						{[{ href: "/posts", title: "Posts" }].map((item) => (
							<MobileLink
								key={item.href}
								href={item.href}
								onOpenChange={setOpen}
							>
								{item.title}
							</MobileLink>
						))}
					</div>
				</ScrollArea>
			</SheetContent>
		</Sheet>
	);
}

interface MobileLinkProps extends LinkProps {
	onOpenChange?: (open: boolean) => void;
	children: React.ReactNode;
	className?: string;
}

function MobileLink({
	href,
	onOpenChange,
	className,
	children,
	...props
}: MobileLinkProps) {
	const router = useRouter();
	return (
		<Link
			href={href}
			onClick={() => {
				router.push(href.toString());
				onOpenChange?.(false);
			}}
			className={cn(className)}
			{...props}
		>
			{children}
		</Link>
	);
}

// src/lib/components/mobile-nav.svelte
<script lang="ts">
  import * as Sheet from "$lib/components/ui/sheet";
  import { SidebarOpen } from "lucide-svelte";
  import { Button } from "$lib/components/ui/button";
  import * as siteConfig from "$lib/config/site";
  import { Icons } from "./icons";
  import MobileLink from "./mobile-link.svelte";

  let open = false;
</script>

<Sheet.Root bind:open>
  <Sheet.Trigger asChild let:builder>
    <Button
      builders={[builder]}
      variant="ghost"
      class="mr-2 px-0 text-base hover:bg-transparent focus-visible:bg-transparent focus-visible:ring-0 focus-visible:ring-offset-0 md:hidden"
    >
      <SidebarOpen class="h-6 w-6" />
      <span class="sr-only">Toggle Menu</span>
      <span class="inline-block font-bold ml-2">Meny</span>
    </Button>
  </Sheet.Trigger>
  <Sheet.Content side="left" class="pt-8 pr-0">
    <MobileLink href="/" class="flex items-center" {open}>
      <Icons.logo class="mr-2 h-4 w-4" />
      <span class="font-bold">{siteConfig.name}</span>
    </MobileLink>
    <div class="my-4 h-[calc(100vh-8rem)] pb-10 pl-6 overflow-auto">
      <div class="flex flex-col space-y-3">
        {#each siteConfig.mainNav as navItem, index (navItem + index.toString())}
          {#if navItem.href}
            <MobileLink href={navItem.href} bind:open>
              {navItem.title}
            </MobileLink>
          {/if}
        {/each}
      </div>
    </div>
  </Sheet.Content>
</Sheet.Root>
